# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_artifact_multimedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='mineType',
            new_name='mimeType',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='date',
        ),
        migrations.AddField(
            model_name='artifact',
            name='year',
            field=models.CharField(default=1800, max_length=10),
            preserve_default=False,
        ),
    ]
