# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_artifact_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='img_url',
        ),
    ]
