# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160402_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='inGallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
