# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('accessionID', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('mineType', models.CharField(max_length=20)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Artifact')),
            ],
        ),
    ]
