# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160327_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
