# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_artifact_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='media')),
                ('mimeType', models.CharField(max_length=20)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Artifact')),
            ],
        ),
    ]
