# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_audiofiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioFiles',
            new_name='AudioFile',
        ),
    ]
